name: "Hello World"
description: "Greet someone and record the time"
inputs:
  organization:
    description: "The name of the organization"
    required: false
  user:
    description: "The name of the user"
    required: false
  projectNumber:
    description: "The number of the project"
    required: false
  token:
    description: |-
      'Token used to authenticate with GitHub API. Default is built-in token but a personal access token may be used for organization or user projects.'
    required: false
    default: ${{github.token}}
outputs:
  isSuccess:
    description: "Is success?"
  statusGroupHtml:
    description: "Status group in html."
runs:
  using: "node16"
  main: "dist/index.js"
