name: build

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint
      - run: npm test -- -- --globals "{\"TOKEN\":\"${{secrets.TEST}}\"}"
      - run: npm run build
