name: project

on:
  push:

jobs:
  project:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}

    steps:
      - name: projectTest
        id: projectTest
        uses: wuzhuobin/project-manager@dev
        with:
          user: wuzhuobin
          projectNumber: 1
          storyPoint: "Story Point"
          status: "Status"
          sprint: "Sprint"
          assigneeWithAt: false
          token: ${{secrets.TEST}}

      - name: Now
        run: echo "NOW=$(date '+%Y-%m-%d %H:%M:%S') (UTC)" >> ${{github.env}}

      - name: test
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: "wuzhuobin"
          labels: "test" # required
          title: test
          body: |-
            :wave: Hi, {{#each assignees}}@{{this}}{{#unless @last}}, {{/unless}}{{/each}}!
            ## test for ${{ env.NOW }}

            ## sprintGroupHtml
            ${{steps.projectTest.outputs.sprintGroupHtml}}

            ## statusGroupHtml
            ${{steps.projectTest.outputs.statusGroupHtml}}

            ## statusGroupWithSprintGroupHtml
            ${{steps.projectTest.outputs.statusGroupWithSprintGroupHtml}}

            ## assigneeGroupHtml
            ${{steps.projectTest.outputs.assigneeGroupHtml}}

            ## assigneeGroupWithSprintGroupHtml
            ${{steps.projectTest.outputs.assigneeGroupWithSprintGroupHtml}}

          pinned: true
          close-previous: true
          linked-comments: true
