name: project

on:
  push:

jobs:
  project:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}

    steps:
      - name: projectTest
        id: projectTest
        uses: wuzhuobin/project-manager@dev
        with:
          user: wuzhuobin
          projectNumber: 1
          token: ${{secrets.TEST}}

      - name: print
        run: echo "The last action result is ${{steps.projectTest.outputs.isSuccess}}." && echo "${{steps.projectTest.outputs.statusGroupHtml}}"

      - name: test
        if: ${{false}}
        uses: imjohnbo/issue-bot@v3
        with:
          title: test
          body: |-
            ${{steps.projectTest.outputs.statusGroupHtml}}
            ${{steps.projectTest.outputs.sprintGroupHtml}}
